### ISSUE TITLE
Duplicate records added in ranking after reentering game

### ISSUE THREAD

**Issue by troilus** [ArcaneCircle/pixel-dungeon#2]
![image](https://github.com/user-attachments/assets/ef2a7cf9-f8a3-44b1-8cf6-ceb907439679)

1. Start a new game
2. Finish a game
3. Go to ranking, there is a new record
4. Exit game by pressing BACK 
5. Reopen game, go to ranking

iOS

**Comment by adbenitez** [comment]
hi, please try with version 1.5.0, maybe the problem is solved

**Comment by troilus** [comment]
https://github.com/user-attachments/assets/5a61a8a9-995b-4387-a150-1b6986baa9d1

1.5.0 still have this problem on iOS( Desktop client does not have this problem), please see the video.

**Comment by adbenitez** [comment]
what version of DC do you have?

**Comment by troilus** [comment]
1.58.6  and 2.8.0, both have this issue.

**Comment by adbenitez** [comment]
IIRC this was a problem of DC iOS version and should be fixed now
